//@flow
export const REQUEST_GET_RECIPES = "REQUEST_GET_RECIPES";
export const RECEIVE_GET_RECIPES = "RECEIVE_GET_RECIPES";

export const FETCH_RECIPES = "FETCH_RECIPES";
export const FETCH_RECIPES_SUCCESS = "FETCH_RECIPES_SUCCESS";
export const FETCH_RECIPES_FAILURE = "FETCH_RECIPES_FAILURE";