//@flow
export const GET_USER_AUTH_TOKEN = "GET_USER_AUTH_TOKEN"

export const REQUEST_AUTH = "REQUEST_AUTH";
export const REQUEST_AUTH_SUCCESS = "REQUEST_AUTH_SUCCESS";
export const REQUEST_AUTH_FAILURE = "REQUEST_AUTH_FAILURE";

export const REQUEST_REGISTRATION = "REQUEST_REGISTRATION";
export const REQUEST_REGISTRATION_SUCCESS = "REQUEST_REGISTRATION_SUCCESS";
export const REQUEST_REGISTRATION_FAILURE = "REQUEST_REGISTRATION_FAILURE";


export const LOGIN_WITH_PROVIDER = "LOGIN_WITH_PROVIDER";